[package]
name = "fair-launch-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.fair-launch]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.0"
default-features = false
