[package]
name = "erc3643-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.erc3643]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.52.0"
default-features = false
