[package]
name = "order-book-factory"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.47.5"

[dev-dependencies.multiversx-sc-scenario]
version = "0.47.5"
