[package]
name = "pair-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.pair-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.4"
default-features = false
