[package]
name = "pair-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.pair-mock]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.51.1"
default-features = false
