[package]
name = "on-chain-claim-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["Vlad Bucur <vlad.bucur@multiversx.com>"]

[dev-dependencies]

[dependencies.on-chain-claim]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.51.1"
default-features = false
