[package]
name = "mvx-game-sc"
version = "0.0.0"
authors = ["Mihai Calin Luca calin.luca@multiversx.com"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.52.3"

[dev-dependencies.multiversx-sc-scenario]
version = "0.52.3"
